deployments/physical/aws: clean
DisciplinaOU/disciplina-profiles pull request #1
Opened 2018-09-07 14:49 UTC by yorickvP

I haven't tested this

2018-09-07 17:37 UTC, mkaito requested changes
99% good

2018-09-07 17:37 UTC, mkaito commented on deployments/physical/aws/default.nix
> +      instanceType = "c5.xlarge";
I mean, yeah, it's DRY, but maybe at least make it `mkDefault`.

2018-09-07 18:22 UTC, yorickvP commented
Apparently, you are supposed to use `subnetGroupIds` if you use `subnets`, which is dumb.

2018-09-07 18:25 UTC, yorickvP commented
> 20:23 <aminechikhaoui> yeah we should fix that I think but for now I think it's that way for historical reasons
> 20:23 <aminechikhaoui> it was that way when I started using nixops :D

2018-09-08 13:27 UTC, mkaito commented
If that assertion is wrong, should it not be removed?

El 7 de septiembre de 2018 19:25:21 GMT+01:00, Yorick <notifications@github.com> escribió:
>> 20:23 <aminechikhaoui> yeah we should fix that I think but for now I
>think it's that way for historical reasons
>> 20:23 <aminechikhaoui> it was that way when I started using nixops :D
>
>
>-- 
>You are receiving this because your review was requested.
>Reply to this email directly or view it on GitHub:
>https://github.com/DisciplinaOU/disciplina-profiles/pull/1#issuecomment-419525867

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

2018-09-12 13:18 UTC, mkaito commented
Update from Slack: nixops is wrong and should be fixed, or we should just fix this PR and merge.

2018-09-12 15:57 UTC, mkaito approved these changes

2018-09-12 16:04 UTC, merged